@startuml
title CadastrarViagem MVC

skinparam classAttributeIconSize 0
hide circle

package "pkg" {
  class Cadastrar {
    + submeterFormulario(): void
  }

  class CadastrarViagemView {
    + submeterFormulario(): void
  }

  class ViagemController {
    + create(dto: ViagemRequestDTO): ResponseEntity<ViagemResponseDTO>
  }

  class ViagemService {
    + create(dto: ViagemRequestDTO): ViagemResponseDTO
  }

  class Viagem {
    - id: Long
    - partida: LocalDateTime
    - chegada: LocalDateTime
    - preco: BigDecimal
    - status: StatusViagem
  }

  Cadastrar <|-- CadastrarViagemView
  CadastrarViagemView -right- ViagemController
  ViagemController -down- ViagemService
  ViagemService -down- Viagem
}
@enduml
