services:
  db:
    container_name: vvv-db
    image: postgres:16-alpine
    ports:   
      - "5432:5432"
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    container_name: vvv-adminer
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
