spring.application.name=VVVSystem

spring.datasource.url=jdbc:postgresql://localhost:5432/vvvsystem
spring.datasource.username=docker
spring.datasource.password=docker
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway Settings
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration